### ISSUE TITLE
Crashes on MacOS with brew and tesseract 4.0.0 installed

### ISSUE THREAD

**Issue by cbertelli** [nguyenq/VietOCR3#10]
When I start OCR it crashes with the following error log:
https://gist.github.com/33fa846ccfa5c829f99439de75cc2d43
Previous versions used to run smoothly with the preceding version of tessseract in the same configuration.
It could be very useful to provide more detailed installation instructions for Linux/BSD/MacOS.

**Comment by nguyenq** [comment]
On Unix/Linux-based systems, please issue `export LC_ALL=C` at the command line before launching the program. You may want to include the statement in `ocr` launch script.

**Comment by nguyenq** [comment]
Sure, we will heed to your suggestions.

Tesseract does not support PDF input out of the box. VietOCR can convert them to images first (via Ghostscript or PDFBox) before the OCR steps.

**Comment by cbertelli** [comment]
Thank you.

About tesseract, I know, but I extracted the images first with pdfimages to
tiff files. Probably when I run VietOCR via command line
(net.sourceforge.vietocr.ConsoleApp
performOCR), I should prepend some environment variable to select preferred
language. If I add the parameters I use for tesseract (-l ita) I got an
error.

**Comment by nguyenq** [comment]
It supports `-l` option, as follows:

`java -jar .\VietOCR.jar .\samples\vietsample.tif out -l vie`

**Comment by cbertelli** [comment]
Thank you, doing so, I get the expected results.
