### ISSUE TITLE
Kannada (kan) output is not readable

### ISSUE THREAD

**Issue by omshivaprakash** [nguyenq/VietOCR3#11]
Hi, 

It would be great if we have a work around to read the OCRéd unicode text for Kannada and other languages on the right handside panel. Please do let me know how it can be fixed. 

<img width="1679" alt="Screenshot 2019-09-28 at 10 11 01" src="https://user-images.githubusercontent.com/115216/65811581-6aa69b80-e1d8-11e9-8bba-24aa9e4ab6ff.png">
<img width="679" alt="Screenshot 2019-09-28 at 10 11 09" src="https://user-images.githubusercontent.com/115216/65811582-6da18c00-e1d8-11e9-8a85-5f98e46fd8d6.png">

**Comment by Shreeshrii** [comment]
The image you have shared seems to show the kannada output. Can you explain the problem being faced?

**Comment by Shreeshrii** [comment]
![kannada](https://user-images.githubusercontent.com/5095331/65817684-f1cf3000-e227-11e9-96db-4e16d2b33782.png)

To me the output looks fine. For me, the default font is showing up as `Arial Unicode MS' on Windows 10.

**Comment by omshivaprakash** [comment]
I’m using it on Mac. I shall check on the font but it has not worked on various kannada fonts.

**Comment by Shreeshrii** [comment]
Are you able to use kannada fonts in other applications on your Mac?

**Comment by omshivaprakash** [comment]
Yes, If I copy paste the text to text editor, notes, mail etc it displays fine. Tried with Arial Unicode MS. No luck

**Comment by Shreeshrii** [comment]
> work around to read the OCRéd unicode text for Kannada and other languages on the right handside panel. 

Does English work?

**Comment by Shreeshrii** [comment]
What is the Mac OS version? Java version?

**Comment by omshivaprakash** [comment]
% java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

Mac OS - Catalina - 10.15  beta - had same issue with Mojave and earlier versions too. 

English Works.

<img width="1641" alt="Screenshot 2019-09-28 at 22 33 32" src="https://user-images.githubusercontent.com/115216/65819916-0c150800-e240-11e9-87ad-f0e1001a21a8.png">

**Comment by Shreeshrii** [comment]
What about Hindi/Sanskrit?

Quan, are there any Mac users who can help?

See https://stackoverflow.com/questions/5994815/rendering-devanagari-ligatures-unicode-in-java-swing-jcomponent-on-mac-os-x/6376670#6376670

**Comment by omshivaprakash** [comment]
<img width="1670" alt="Screenshot 2019-09-28 at 23 13 22" src="https://user-images.githubusercontent.com/115216/65820370-9449dc00-e245-11e9-9a4b-1face969b6ac.png">

Hindi Works fine.

**Comment by nguyenq** [comment]
The program uses Java's native text component to display the output text. We have no Mac to test this issue. Based on the suggestions from SO posts, can you try to use Quartz renderer?

`javaw -Xms128m -Xmx2048m -Dapple.awt.graphics.UseQuartz="true" -jar VietOCR.jar`

**Comment by omshivaprakash** [comment]
javaw didn't work. Tried the above command with java - no luck.

<img width="1678" alt="Screenshot 2019-09-29 at 00 07 03" src="https://user-images.githubusercontent.com/115216/65820965-14277480-e24d-11e9-8fae-2366b2ce47b0.png">

**Comment by nguyenq** [comment]
Sorry, copy&paste error. It was meant to be `java` command. It seems to be a OSX-Java-Kannada rendering issue. We suggest that you use another editor for viewing or editing Kannada script.

**Comment by Shreeshrii** [comment]
>Hindi Works fine.

Actually even that has some errors related to the glyphs for compound letters eg. check 
क्यूं
ब्लॉग
दर्जा

Seems to be a rendering problem on Mac + Java for complex script.

**Comment by omshivaprakash** [comment]
@Shreeshrii Thats correct. Could only OCR last two words 

<img width="76" alt="Screenshot 2019-09-29 at 11 05 27" src="https://user-images.githubusercontent.com/115216/65826826-0dc6e600-e2a9-11e9-86e4-7160c19ea00c.png">

**Comment by omshivaprakash** [comment]
% java -version
java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)
Seem to have resolved the issue. 

Thank you for pointing this out. @nguyenq 

<img width="1680" alt="Screenshot 2019-09-29 at 15 06 46" src="https://user-images.githubusercontent.com/115216/65830179-c8b3ab80-e2ca-11e9-825f-d5f0229bc074.png">
