### ISSUE TITLE
Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed

### ISSUE THREAD

**Issue by omshivaprakash** [nguyenq/VietOCR3#13]
Any quick resolution to the following case? Attaching the sample PDF used for this test. 
VietOCR version 5.5.1

[ಉಕ್ರೇನಿನ_ಜಾನಪದ_ಕಥೆಗಳು (dragged) 12.pdf](https://github.com/nguyenq/VietOCR3/files/3760049/_._.dragged.12.pdf)

08:12:44.400 [SwingWorker-pool-1-thread-2] ERROR org.apache.pdfbox.contentstream.PDFStreamEngine - Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
08:12:44.401 [SwingWorker-pool-1-thread-2] ERROR org.apache.pdfbox.contentstream.PDFStreamEngine - Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed
08:12:47.981 [Finalizer] DEBUG org.apache.pdfbox.io.ScratchFileBuffer - ScratchFileBuffer not closed!
08:12:47.981 [Finalizer] DEBUG org.apache.pdfbox.io.ScratchFileBuffer - ScratchFileBuffer not closed!
08:12:47.981 [Finalizer] DEBUG org.apache.pdfbox.io.ScratchFileBuffer - ScratchFileBuffer not closed!

**Comment by nguyenq** [comment]
It will need to add [`jai-imageio-jpeg2000 library`](https://mvnrepository.com/artifact/com.github.jai-imageio/jai-imageio-jpeg2000) library. The next release will include it.

In the meantime, you can install Ghostscript to read JPEG2000.

**Comment by nguyenq** [comment]
Fixed in [Release-5.5.3](https://github.com/nguyenq/VietOCR3/releases/tag/Release-5.5.3).
