### ISSUE TITLE
String improvement suggestion

### ISSUE THREAD

**Issue by rimas-kudelis** [nguyenq/VietOCR3#17]
I have had this feedback item on Transifex from one of the localizers since quite a while ago. Proxying it over here. It's about the following string in the README: 
https://github.com/nguyenq/VietOCR3/blob/82191c20b26c9c1725151eefe5713654b7b7afba/readme.html#L69
The feedback is:
> Better English suggestion "In order to use the scan functionality the following SANE packages are required for Linux based operating systems:"

**Comment by nguyenq** [comment]
They essentially mean the same.

**Comment by rimas-kudelis** [comment]
I know. It's up to you whether to accept that suggestion.
