### ISSUE TITLE
Error when running `java -jar ...`

### ISSUE THREAD

**Issue by corneliusroemer** [nguyenq/VietOCR3#22]
I get the following error on Mac:
![image](https://user-images.githubusercontent.com/25161793/135375505-92b33187-9e4b-470c-bd10-979373c3f69f.png)

Do I need to install any dependencies? If so which? The Readme doesn't specify any.

**Comment by nguyenq** [comment]
Yes, you would need Tesseract installed on your machine.

https://tesseract-ocr.github.io/tessdoc/Installation.html
