### ISSUE TITLE
Unable to install the language trained data 

### ISSUE THREAD

**Issue by omshivaprakash** [nguyenq/VietOCR3#23]
Unable to install the language. It fails. Looks like the raw folder has been removed from the tesseract repo. Please fix. 

Caused by: java.io.FileNotFoundException: https://github.com/tesseract-ocr/tessdata_fast/raw/master/script/Kannada.traineddata
<img width="1239" alt="Screenshot 2021-11-10 at 10 49 40 PM" src="https://user-images.githubusercontent.com/115216/141161542-0e4bf8b4-2124-49c2-980e-82a4b8f91342.png">
<img width="567" alt="Screenshot 2021-11-10 at 10 50 01 PM" src="https://user-images.githubusercontent.com/115216/141161600-c1983ff3-8827-4ac5-ab33-e9a965f28414.png">
% java -version
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

**Comment by nguyenq** [comment]
Yes, the links were changed on Tesseract project, and we only recently became aware of it and already addressed it in commit https://github.com/nguyenq/VietOCR3/commit/af8945e6edd4f6b737ece53e69bc054f29cea963 . Will soon publish a release for it.

Thanks.
