### ISSUE TITLE
How to open several images

### ISSUE THREAD

**Issue by vivadavid** [nguyenq/VietOCR3#25]
Hi,

I know that in Bulk OCR, you can process many images at the same time, but I'd like to be able to have more than one image opened on the screen to perform certain operations before the OCR. If I open one image and then another one, the first one is closed, so I can only have one at the same time. Is there a way to do this?

Thanks!

**Comment by nguyenq** [comment]
The app only operates on individual image files. You can stuff separate images into a multi-page TIFF and load that.

**Comment by vivadavid** [comment]
> The app only operates on individual image files. You can stuff separate images into a multi-page TIFF and load that.

Thanks for your reply, and I'd like to kindly request this feature for a future release!

**Comment by vivadavid** [comment]
Hi,

I wanted to kindly ask if it's been reconsidered adding this feature.

Thanks in advance!

**Comment by nguyenq** [comment]
Implemented in commit 70ea8dd9ff1c4eaa9f46845eedef9aa2368e132a.

**Comment by vivadavid** [comment]
> Implemented in commit [70ea8dd](https://github.com/nguyenq/VietOCR3/commit/70ea8dd9ff1c4eaa9f46845eedef9aa2368e132a).

Great news: thanks!

**Comment by nguyenq** [comment]
@vivadavid Press the Shift key as you open another image to add to the existing ones.

The new version will be released in the next few days as I finalize the Tesseract build. Thanks.

**Comment by vivadavid** [comment]
Hi,

I've just tried version 6.7.13 and it works as you described. Thanks: now I can have more than one image open at the same time.

However, I'd like to make two comments:

1. I was wondering if it would be possible to make adding an image the default behaviour instead of having to press SHIFT. Normally if you have a picture open and you click to open another one, that means you're interested in processing both images. Otherwise, you can just close the programme and open it again.
2. If you need to process a large number of images, adding them one by one isn't ideal. It'd be great if multiple images could be selected on one go.

In any case, I appreciate the improvements.

**Comment by vivadavid** [comment]
Also, I have a question.

I always thought the .NET version you can download on Sourceforge was behind in features, as the version number is lower, but today I had a look at the changelog for 6.11.0 for the .NET version and it's the same as the changelog for 6.13.0 for the Java version.

Is there a reason why they don't have the same version number? Users might be inclined to think that the Java version is more modern.

Thanks.

**Comment by nguyenq** [comment]
One version (Java or .NET) of the program may have more revisions (for instance, due to bug fixes, dependency updates, etc.) than the other.

The normal behavior of a single-document interface (SDI) application is opening one file at a time; a previously loaded file will be unloaded. A typical example is MS Notepad.

The File Dialog can support selection of multiple files. We can consider enabling the capability in the next release, if this is desired, but it could introduce more complexity in the code in handling the multiple files.

**Comment by nguyenq** [comment]
@vivadavid I've added support for opening multiple file selection. Can you help test before I release them?

Thanks.

[VietOCR.NET-6.11.1_64.zip](https://github.com/nguyenq/VietOCR3/files/14624323/VietOCR.NET-6.11.1_64.zip)
[VietOCR-6.13.1.zip](https://github.com/nguyenq/VietOCR3/files/14624325/VietOCR-6.13.1.zip)

**Comment by vivadavid** [comment]
Thanks, @nguyenq ,

I've tested the portable version. I can actually open several images at once, but when I click on _OCR_, the action only affects the current image. The main purpose of opening several images is to be able to process them at the same time, so it'd be extremely useful to have a way to select **some** images, as well as **all** the images.

Also, the current way to show that an image is selected is by drawing a dotted-line, which can be not that easy to see. What about adding some kind of effect to the thumbnail?

**Comment by nguyenq** [comment]
The OCR All Pages item under Command menu serves that purpose.

We'll add some kind of highlight the thumbnails to better indicate the currently selected image in future releases.

**Comment by vivadavid** [comment]
Sorry, you are right: my eyes were placed on the icon and I forgot about the "OCR all pages" command.

Highlighting the current page would be great: thanks!

**Comment by vivadavid** [comment]
I've just tested the .NET version and it works well: I can select several images.

**Comment by nguyenq** [comment]
Marking the current thumbnail has been added to the releases.

Thank you very much for your input.

**Comment by vivadavid** [comment]
Thank you for implementing the most recent changes, @nguyenq : they made VietOCR even better!

So, for a Windows user like me: is there a particular reason to choose either the Java version or the .NET version?

**Comment by nguyenq** [comment]
While they are equally capable, the Java version can run across different platforms -- Windows, Linux, and MacOS. The .NET version, based on WPF, for being a native Windows desktop application, tends to look better on Windows. WPF apps are resolution independent, scaling the UI according to the screen resolution.

**Comment by vivadavid** [comment]
Thanks for the information. Should I expect the same kind of performance on both versions then? The UI on the Java version, which is the one I normally use, looks fine to me.

**Comment by nguyenq** [comment]
Yes, they have the same functionality.
