### ISSUE TITLE
x.DangAmbigs.txt not taken into account with bulk OCR

### ISSUE THREAD

**Issue by mercibe** [nguyenq/VietOCR3#28]
Custom text replacement scheme via a UTF-8-encoded tab-delimited text file named <code>x.DangAmbigs.txt</code> doesn't seem to be triggered in bulk OCR operation even if Post Processing is checked in Options > Bulk/Batch Options

**Comment by nguyenq** [comment]
Fixed by commit https://github.com/nguyenq/VietOCR3/commit/1761cbcdaf1ede25b999032a6ffad999fa4c24e5.

Thank you!

**Comment by mercibe** [comment]
Thank you very much!
