### ISSUE TITLE
Displaying fragmented regions does not work

### ISSUE THREAD

**Issue by Pawwwle** [nguyenq/VietOCR3#29]
Displaying fragmented regions does not work.

<img width="960" alt="Zrzut ekranu 2023-08-29 123712" src="https://github.com/nguyenq/VietOCR3/assets/115624603/f594be69-647e-425f-95e2-afbee4f331af">

**Comment by nguyenq** [comment]
The issue should be opened under [VietOCRwpf](https://github.com/nguyenq/VietOCRwpf) project since the program is .NET version.

The regions just reflect the results of Tesseract OCR engine's segmentation on the image.

**Comment by Pawwwle** [comment]
I also tested the version VitOCR3 . In this version it doesn't work at all. :(

**Comment by nguyenq** [comment]
@Pawwwle We were unable to reproduce the issue. Can you try with the latest versions? If the problem still persists, please include a sample image. The box coordinates are generated by Tesseract OCR engine itself.
