### ISSUE TITLE
How to use training data ?

### ISSUE THREAD

**Issue by mozartvn** [nguyenq/VietOCR3#4]
Dear mr NguyenQ.

please help me resolve the following problem

1. How to unpackage training data in this folder ?https://github.com/nguyenq/VietOCR3/tree/master/tesseract-ocr/tessdata
2. What is structure ?

I want to use it data for training my OCR model.

Thanks !

**Comment by nguyenq** [comment]
[Training Tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki/TrainingTesseract) provides full details on the subject.
