### ISSUE TITLE
how can I use it on windows?

### ISSUE THREAD

**Issue by saurabhbidwai** [nguyenq/VietOCR3#9]
Anyone can help me to start working on it on the windows system?

**Comment by nguyenq** [comment]
Download and unzip the distribution. You need JRE 8 or greater installed on your machine to run it.

**Comment by nguyenq** [comment]
Can you get it to run on your Windows system?

**Comment by saurabhbidwai** [comment]
Yes @nguyenq , Thanks
I'll get back to u whenever I face any difficulty.
